### ISSUE TITLE
'2. Page Builder Blocks - iii. Creating a custom block' does not exist

### ISSUE THREAD

**Issue by johnhughes1984** [genecommerce/Blue-Foot-Documentation#3]
The page referenced under this section 404s: https://github.com/genecommerce/Blue-Foot-Documentation/blob/master/PageBuilderBlocks/CustomBlock.md

I can't see the page under https://github.com/genecommerce/Blue-Foot-Documentation/blob/master/PageBuilderBlocks either.

Has this page not been written yet or just missing?

**Comment by DaveMacaulay** [comment]
Thanks for letting us know about the missing article. I'll be sure to get it reinstated.

**Comment by DaveMacaulay** [comment]
Resolved by #4
